//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.19 at 10:23:56 AM GMT 
//


package batch.digital.hoares.products;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for BalanceType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BalanceType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="EODFlag" type="{http://hoares.digital.batch/Products.xsd}Max50Text" minOccurs="0"/>
 *         &lt;element name="ledger" type="{http://hoares.digital.batch/Products.xsd}BalanceAmount" minOccurs="0"/>
 *         &lt;element name="available" type="{http://hoares.digital.batch/Products.xsd}BalanceAmount" minOccurs="0"/>
 *         &lt;element name="average" type="{http://hoares.digital.batch/Products.xsd}BalanceAmount" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BalanceType", propOrder = {
    "eodFlag",
    "ledger",
    "available",
    "average"
})
public class BalanceType {

    @XmlElement(name = "EODFlag")
    protected String eodFlag;
    protected BigDecimal ledger;
    protected BigDecimal available;
    protected BigDecimal average;

    /**
     * Gets the value of the eodFlag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEODFlag() {
        return eodFlag;
    }

    /**
     * Sets the value of the eodFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEODFlag(String value) {
        this.eodFlag = value;
    }

    /**
     * Gets the value of the ledger property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getLedger() {
        return ledger;
    }

    /**
     * Sets the value of the ledger property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setLedger(BigDecimal value) {
        this.ledger = value;
    }

    /**
     * Gets the value of the available property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getAvailable() {
        return available;
    }

    /**
     * Sets the value of the available property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setAvailable(BigDecimal value) {
        this.available = value;
    }

    /**
     * Gets the value of the average property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getAverage() {
        return average;
    }

    /**
     * Sets the value of the average property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setAverage(BigDecimal value) {
        this.average = value;
    }

}
