//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.19 at 10:23:56 AM GMT 
//


package batch.digital.hoares.products;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for DateType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DateType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="open" type="{http://hoares.digital.batch/Products.xsd}ISODate" minOccurs="0"/>
 *         &lt;element name="close" type="{http://hoares.digital.batch/Products.xsd}ISODate" minOccurs="0"/>
 *         &lt;element name="lastStatement" type="{http://hoares.digital.batch/Products.xsd}ISODate" minOccurs="0"/>
 *         &lt;element name="minRepaymentDueDate" type="{http://hoares.digital.batch/Products.xsd}ISODate" minOccurs="0"/>
 *         &lt;element name="system" type="{http://hoares.digital.batch/Products.xsd}ISODate" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DateType", propOrder = {
    "open",
    "close",
    "lastStatement",
    "minRepaymentDueDate",
    "system"
})
public class DateType {

    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar open;
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar close;
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar lastStatement;
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar minRepaymentDueDate;
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar system;

    /**
     * Gets the value of the open property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getOpen() {
        return open;
    }

    /**
     * Sets the value of the open property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setOpen(XMLGregorianCalendar value) {
        this.open = value;
    }

    /**
     * Gets the value of the close property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getClose() {
        return close;
    }

    /**
     * Sets the value of the close property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setClose(XMLGregorianCalendar value) {
        this.close = value;
    }

    /**
     * Gets the value of the lastStatement property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getLastStatement() {
        return lastStatement;
    }

    /**
     * Sets the value of the lastStatement property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setLastStatement(XMLGregorianCalendar value) {
        this.lastStatement = value;
    }

    /**
     * Gets the value of the minRepaymentDueDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getMinRepaymentDueDate() {
        return minRepaymentDueDate;
    }

    /**
     * Sets the value of the minRepaymentDueDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setMinRepaymentDueDate(XMLGregorianCalendar value) {
        this.minRepaymentDueDate = value;
    }

    /**
     * Gets the value of the system property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getSystem() {
        return system;
    }

    /**
     * Sets the value of the system property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setSystem(XMLGregorianCalendar value) {
        this.system = value;
    }

}
