//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.19 at 10:23:56 AM GMT 
//


package batch.digital.hoares.products;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for DealType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DealType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="deal" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="refID" type="{http://hoares.digital.batch/Products.xsd}Max50Text"/>
 *                   &lt;element name="seq" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="amount" type="{http://hoares.digital.batch/Products.xsd}TransactionAmount"/>
 *                   &lt;element name="dealDate" type="{http://hoares.digital.batch/Products.xsd}ISODate"/>
 *                   &lt;element name="maturityDate" type="{http://hoares.digital.batch/Products.xsd}ISODate"/>
 *                   &lt;element name="currencyCode" type="{http://hoares.digital.batch/Products.xsd}CurrencyCode"/>
 *                   &lt;element name="interestRate" type="{http://hoares.digital.batch/Products.xsd}InterestRate"/>
 *                   &lt;element name="interestGrossMaturity" type="{http://hoares.digital.batch/Products.xsd}InterestAmount"/>
 *                   &lt;element name="interestGrossPaid" type="{http://hoares.digital.batch/Products.xsd}InterestAmount"/>
 *                   &lt;element name="interestNetPaid" type="{http://hoares.digital.batch/Products.xsd}InterestAmount"/>
 *                   &lt;element name="interestNetAccrued" type="{http://hoares.digital.batch/Products.xsd}InterestAmount"/>
 *                   &lt;element name="status" type="{http://hoares.digital.batch/Products.xsd}Max50Text"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DealType", propOrder = {
    "deal"
})
public class DealType {

    @XmlElement(required = true)
    protected List<DealType.Deal> deal;

    /**
     * Gets the value of the deal property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the deal property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDeal().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DealType.Deal }
     * 
     * 
     */
    public List<DealType.Deal> getDeal() {
        if (deal == null) {
            deal = new ArrayList<DealType.Deal>();
        }
        return this.deal;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="refID" type="{http://hoares.digital.batch/Products.xsd}Max50Text"/>
     *         &lt;element name="seq" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="amount" type="{http://hoares.digital.batch/Products.xsd}TransactionAmount"/>
     *         &lt;element name="dealDate" type="{http://hoares.digital.batch/Products.xsd}ISODate"/>
     *         &lt;element name="maturityDate" type="{http://hoares.digital.batch/Products.xsd}ISODate"/>
     *         &lt;element name="currencyCode" type="{http://hoares.digital.batch/Products.xsd}CurrencyCode"/>
     *         &lt;element name="interestRate" type="{http://hoares.digital.batch/Products.xsd}InterestRate"/>
     *         &lt;element name="interestGrossMaturity" type="{http://hoares.digital.batch/Products.xsd}InterestAmount"/>
     *         &lt;element name="interestGrossPaid" type="{http://hoares.digital.batch/Products.xsd}InterestAmount"/>
     *         &lt;element name="interestNetPaid" type="{http://hoares.digital.batch/Products.xsd}InterestAmount"/>
     *         &lt;element name="interestNetAccrued" type="{http://hoares.digital.batch/Products.xsd}InterestAmount"/>
     *         &lt;element name="status" type="{http://hoares.digital.batch/Products.xsd}Max50Text"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "refID",
        "seq",
        "amount",
        "dealDate",
        "maturityDate",
        "currencyCode",
        "interestRate",
        "interestGrossMaturity",
        "interestGrossPaid",
        "interestNetPaid",
        "interestNetAccrued",
        "status"
    })
    public static class Deal {

        @XmlElement(required = true)
        protected String refID;
        protected int seq;
        @XmlElement(required = true)
        protected BigDecimal amount;
        @XmlElement(required = true)
        @XmlSchemaType(name = "date")
        protected XMLGregorianCalendar dealDate;
        @XmlElement(required = true)
        @XmlSchemaType(name = "date")
        protected XMLGregorianCalendar maturityDate;
        @XmlElement(required = true)
        protected String currencyCode;
        @XmlElement(required = true)
        protected BigDecimal interestRate;
        @XmlElement(required = true)
        protected BigDecimal interestGrossMaturity;
        @XmlElement(required = true)
        protected BigDecimal interestGrossPaid;
        @XmlElement(required = true)
        protected BigDecimal interestNetPaid;
        @XmlElement(required = true)
        protected BigDecimal interestNetAccrued;
        @XmlElement(required = true)
        protected String status;

        /**
         * Gets the value of the refID property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRefID() {
            return refID;
        }

        /**
         * Sets the value of the refID property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRefID(String value) {
            this.refID = value;
        }

        /**
         * Gets the value of the seq property.
         * 
         */
        public int getSeq() {
            return seq;
        }

        /**
         * Sets the value of the seq property.
         * 
         */
        public void setSeq(int value) {
            this.seq = value;
        }

        /**
         * Gets the value of the amount property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getAmount() {
            return amount;
        }

        /**
         * Sets the value of the amount property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setAmount(BigDecimal value) {
            this.amount = value;
        }

        /**
         * Gets the value of the dealDate property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getDealDate() {
            return dealDate;
        }

        /**
         * Sets the value of the dealDate property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setDealDate(XMLGregorianCalendar value) {
            this.dealDate = value;
        }

        /**
         * Gets the value of the maturityDate property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getMaturityDate() {
            return maturityDate;
        }

        /**
         * Sets the value of the maturityDate property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setMaturityDate(XMLGregorianCalendar value) {
            this.maturityDate = value;
        }

        /**
         * Gets the value of the currencyCode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCurrencyCode() {
            return currencyCode;
        }

        /**
         * Sets the value of the currencyCode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCurrencyCode(String value) {
            this.currencyCode = value;
        }

        /**
         * Gets the value of the interestRate property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getInterestRate() {
            return interestRate;
        }

        /**
         * Sets the value of the interestRate property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setInterestRate(BigDecimal value) {
            this.interestRate = value;
        }

        /**
         * Gets the value of the interestGrossMaturity property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getInterestGrossMaturity() {
            return interestGrossMaturity;
        }

        /**
         * Sets the value of the interestGrossMaturity property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setInterestGrossMaturity(BigDecimal value) {
            this.interestGrossMaturity = value;
        }

        /**
         * Gets the value of the interestGrossPaid property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getInterestGrossPaid() {
            return interestGrossPaid;
        }

        /**
         * Sets the value of the interestGrossPaid property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setInterestGrossPaid(BigDecimal value) {
            this.interestGrossPaid = value;
        }

        /**
         * Gets the value of the interestNetPaid property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getInterestNetPaid() {
            return interestNetPaid;
        }

        /**
         * Sets the value of the interestNetPaid property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setInterestNetPaid(BigDecimal value) {
            this.interestNetPaid = value;
        }

        /**
         * Gets the value of the interestNetAccrued property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getInterestNetAccrued() {
            return interestNetAccrued;
        }

        /**
         * Sets the value of the interestNetAccrued property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setInterestNetAccrued(BigDecimal value) {
            this.interestNetAccrued = value;
        }

        /**
         * Gets the value of the status property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getStatus() {
            return status;
        }

        /**
         * Sets the value of the status property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setStatus(String value) {
            this.status = value;
        }

    }

}
