//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.19 at 10:23:56 AM GMT 
//


package batch.digital.hoares.products;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the batch.digital.hoares.products package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Product_QNAME = new QName("http://hoares.digital.batch/Products.xsd", "product");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: batch.digital.hoares.products
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link DealType }
     * 
     */
    public DealType createDealType() {
        return new DealType();
    }

    /**
     * Create an instance of {@link HoldingType }
     * 
     */
    public HoldingType createHoldingType() {
        return new HoldingType();
    }

    /**
     * Create an instance of {@link SubProductType }
     * 
     */
    public SubProductType createSubProductType() {
        return new SubProductType();
    }

    /**
     * Create an instance of {@link TransactionType }
     * 
     */
    public TransactionType createTransactionType() {
        return new TransactionType();
    }

    /**
     * Create an instance of {@link ProductType }
     * 
     */
    public ProductType createProductType() {
        return new ProductType();
    }

    /**
     * Create an instance of {@link BalanceType }
     * 
     */
    public BalanceType createBalanceType() {
        return new BalanceType();
    }

    /**
     * Create an instance of {@link AdditionalDetailsType }
     * 
     */
    public AdditionalDetailsType createAdditionalDetailsType() {
        return new AdditionalDetailsType();
    }

    /**
     * Create an instance of {@link DateType }
     * 
     */
    public DateType createDateType() {
        return new DateType();
    }

    /**
     * Create an instance of {@link LimitType }
     * 
     */
    public LimitType createLimitType() {
        return new LimitType();
    }

    /**
     * Create an instance of {@link InterestType }
     * 
     */
    public InterestType createInterestType() {
        return new InterestType();
    }

    /**
     * Create an instance of {@link ProductDetailsType }
     * 
     */
    public ProductDetailsType createProductDetailsType() {
        return new ProductDetailsType();
    }

    /**
     * Create an instance of {@link DealType.Deal }
     * 
     */
    public DealType.Deal createDealTypeDeal() {
        return new DealType.Deal();
    }

    /**
     * Create an instance of {@link HoldingType.Holding }
     * 
     */
    public HoldingType.Holding createHoldingTypeHolding() {
        return new HoldingType.Holding();
    }

    /**
     * Create an instance of {@link SubProductType.SubProduct }
     * 
     */
    public SubProductType.SubProduct createSubProductTypeSubProduct() {
        return new SubProductType.SubProduct();
    }

    /**
     * Create an instance of {@link TransactionType.Transaction }
     * 
     */
    public TransactionType.Transaction createTransactionTypeTransaction() {
        return new TransactionType.Transaction();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ProductType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://hoares.digital.batch/Products.xsd", name = "product")
    public JAXBElement<ProductType> createProduct(ProductType value) {
        return new JAXBElement<ProductType>(_Product_QNAME, ProductType.class, null, value);
    }

}
