//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.19 at 10:23:56 AM GMT 
//


package batch.digital.hoares.products;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *         Schema will have product details, transactions, deals, holdings etc. 
 *       
 * 
 * <p>Java class for ProductType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ProductType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="productDetails" type="{http://hoares.digital.batch/Products.xsd}ProductDetailsType"/>
 *         &lt;element name="transactions" type="{http://hoares.digital.batch/Products.xsd}TransactionType" minOccurs="0"/>
 *         &lt;element name="deals" type="{http://hoares.digital.batch/Products.xsd}DealType" minOccurs="0"/>
 *         &lt;element name="holdings" type="{http://hoares.digital.batch/Products.xsd}HoldingType" minOccurs="0"/>
 *         &lt;element name="subProducts" type="{http://hoares.digital.batch/Products.xsd}SubProductType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlRootElement(name="product")
@XmlType(name = "ProductType", propOrder = {
    "productDetails",
    "transactions",
    "deals",
    "holdings",
    "subProducts"
})
public class ProductType {

    @XmlElement(required = true)
    protected ProductDetailsType productDetails;
    protected TransactionType transactions;
    protected DealType deals;
    protected HoldingType holdings;
    protected SubProductType subProducts;

    /**
     * Gets the value of the productDetails property.
     * 
     * @return
     *     possible object is
     *     {@link ProductDetailsType }
     *     
     */
    public ProductDetailsType getProductDetails() {
        return productDetails;
    }

    /**
     * Sets the value of the productDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProductDetailsType }
     *     
     */
    public void setProductDetails(ProductDetailsType value) {
        this.productDetails = value;
    }

    /**
     * Gets the value of the transactions property.
     * 
     * @return
     *     possible object is
     *     {@link TransactionType }
     *     
     */
    public TransactionType getTransactions() {
        return transactions;
    }

    /**
     * Sets the value of the transactions property.
     * 
     * @param value
     *     allowed object is
     *     {@link TransactionType }
     *     
     */
    public void setTransactions(TransactionType value) {
        this.transactions = value;
    }

    /**
     * Gets the value of the deals property.
     * 
     * @return
     *     possible object is
     *     {@link DealType }
     *     
     */
    public DealType getDeals() {
        return deals;
    }

    /**
     * Sets the value of the deals property.
     * 
     * @param value
     *     allowed object is
     *     {@link DealType }
     *     
     */
    public void setDeals(DealType value) {
        this.deals = value;
    }

    /**
     * Gets the value of the holdings property.
     * 
     * @return
     *     possible object is
     *     {@link HoldingType }
     *     
     */
    public HoldingType getHoldings() {
        return holdings;
    }

    /**
     * Sets the value of the holdings property.
     * 
     * @param value
     *     allowed object is
     *     {@link HoldingType }
     *     
     */
    public void setHoldings(HoldingType value) {
        this.holdings = value;
    }

    /**
     * Gets the value of the subProducts property.
     * 
     * @return
     *     possible object is
     *     {@link SubProductType }
     *     
     */
    public SubProductType getSubProducts() {
        return subProducts;
    }

    /**
     * Sets the value of the subProducts property.
     * 
     * @param value
     *     allowed object is
     *     {@link SubProductType }
     *     
     */
    public void setSubProducts(SubProductType value) {
        this.subProducts = value;
    }

}
