//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.19 at 10:23:56 AM GMT 
//


package batch.digital.hoares.products;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for TransactionType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TransactionType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="transaction" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="refID" type="{http://hoares.digital.batch/Products.xsd}Max256Text"/>
 *                   &lt;element name="code" type="{http://hoares.digital.batch/Products.xsd}Max256Text"/>
 *                   &lt;element name="type" type="{http://hoares.digital.batch/Products.xsd}CreditDebitCode"/>
 *                   &lt;element name="amount" type="{http://hoares.digital.batch/Products.xsd}TransactionAmount"/>
 *                   &lt;element name="currencyCode" type="{http://hoares.digital.batch/Products.xsd}CurrencyCode"/>
 *                   &lt;element name="postingDate" type="{http://hoares.digital.batch/Products.xsd}ISODate"/>
 *                   &lt;element name="valueDate" type="{http://hoares.digital.batch/Products.xsd}ISODate"/>
 *                   &lt;element name="narrative" type="{http://hoares.digital.batch/Products.xsd}Max256Text"/>
 *                   &lt;element name="additionalRef1" type="{http://hoares.digital.batch/Products.xsd}Max1000Text" minOccurs="0"/>
 *                   &lt;element name="additionalRef2" type="{http://hoares.digital.batch/Products.xsd}Max1000Text" minOccurs="0"/>
 *                   &lt;element name="additionalRef3" type="{http://hoares.digital.batch/Products.xsd}Max1000Text" minOccurs="0"/>
 *                   &lt;element name="additionalRef4" type="{http://hoares.digital.batch/Products.xsd}Max1000Text" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TransactionType", propOrder = {
    "transaction"
})
public class TransactionType {

    @XmlElement(required = true)
    protected List<TransactionType.Transaction> transaction;

    /**
     * Gets the value of the transaction property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the transaction property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTransaction().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TransactionType.Transaction }
     * 
     * 
     */
    public List<TransactionType.Transaction> getTransaction() {
        if (transaction == null) {
            transaction = new ArrayList<TransactionType.Transaction>();
        }
        return this.transaction;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="refID" type="{http://hoares.digital.batch/Products.xsd}Max256Text"/>
     *         &lt;element name="code" type="{http://hoares.digital.batch/Products.xsd}Max256Text"/>
     *         &lt;element name="type" type="{http://hoares.digital.batch/Products.xsd}CreditDebitCode"/>
     *         &lt;element name="amount" type="{http://hoares.digital.batch/Products.xsd}TransactionAmount"/>
     *         &lt;element name="currencyCode" type="{http://hoares.digital.batch/Products.xsd}CurrencyCode"/>
     *         &lt;element name="postingDate" type="{http://hoares.digital.batch/Products.xsd}ISODate"/>
     *         &lt;element name="valueDate" type="{http://hoares.digital.batch/Products.xsd}ISODate"/>
     *         &lt;element name="narrative" type="{http://hoares.digital.batch/Products.xsd}Max256Text"/>
     *         &lt;element name="additionalRef1" type="{http://hoares.digital.batch/Products.xsd}Max1000Text" minOccurs="0"/>
     *         &lt;element name="additionalRef2" type="{http://hoares.digital.batch/Products.xsd}Max1000Text" minOccurs="0"/>
     *         &lt;element name="additionalRef3" type="{http://hoares.digital.batch/Products.xsd}Max1000Text" minOccurs="0"/>
     *         &lt;element name="additionalRef4" type="{http://hoares.digital.batch/Products.xsd}Max1000Text" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "refID",
        "code",
        "type",
        "amount",
        "currencyCode",
        "postingDate",
        "valueDate",
        "narrative",
        "additionalRef1",
        "additionalRef2",
        "additionalRef3",
        "additionalRef4"
    })
    public static class Transaction {

        @XmlElement(required = true)
        protected String refID;
        @XmlElement(required = true)
        protected String code;
        @XmlElement(required = true)
        @XmlSchemaType(name = "string")
        protected CreditDebitCode type;
        @XmlElement(required = true)
        protected BigDecimal amount;
        @XmlElement(required = true)
        protected String currencyCode;
        @XmlElement(required = true)
        @XmlSchemaType(name = "date")
        protected XMLGregorianCalendar postingDate;
        @XmlElement(required = true)
        @XmlSchemaType(name = "date")
        protected XMLGregorianCalendar valueDate;
        @XmlElement(required = true)
        protected String narrative;
        protected String additionalRef1;
        protected String additionalRef2;
        protected String additionalRef3;
        protected String additionalRef4;

        /**
         * Gets the value of the refID property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRefID() {
            return refID;
        }

        /**
         * Sets the value of the refID property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRefID(String value) {
            this.refID = value;
        }

        /**
         * Gets the value of the code property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCode() {
            return code;
        }

        /**
         * Sets the value of the code property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCode(String value) {
            this.code = value;
        }

        /**
         * Gets the value of the type property.
         * 
         * @return
         *     possible object is
         *     {@link CreditDebitCode }
         *     
         */
        public CreditDebitCode getType() {
            return type;
        }

        /**
         * Sets the value of the type property.
         * 
         * @param value
         *     allowed object is
         *     {@link CreditDebitCode }
         *     
         */
        public void setType(CreditDebitCode value) {
            this.type = value;
        }

        /**
         * Gets the value of the amount property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getAmount() {
            return amount;
        }

        /**
         * Sets the value of the amount property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setAmount(BigDecimal value) {
            this.amount = value;
        }

        /**
         * Gets the value of the currencyCode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCurrencyCode() {
            return currencyCode;
        }

        /**
         * Sets the value of the currencyCode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCurrencyCode(String value) {
            this.currencyCode = value;
        }

        /**
         * Gets the value of the postingDate property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getPostingDate() {
            return postingDate;
        }

        /**
         * Sets the value of the postingDate property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setPostingDate(XMLGregorianCalendar value) {
            this.postingDate = value;
        }

        /**
         * Gets the value of the valueDate property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getValueDate() {
            return valueDate;
        }

        /**
         * Sets the value of the valueDate property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setValueDate(XMLGregorianCalendar value) {
            this.valueDate = value;
        }

        /**
         * Gets the value of the narrative property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getNarrative() {
            return narrative;
        }

        /**
         * Sets the value of the narrative property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setNarrative(String value) {
            this.narrative = value;
        }

        /**
         * Gets the value of the additionalRef1 property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAdditionalRef1() {
            return additionalRef1;
        }

        /**
         * Sets the value of the additionalRef1 property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAdditionalRef1(String value) {
            this.additionalRef1 = value;
        }

        /**
         * Gets the value of the additionalRef2 property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAdditionalRef2() {
            return additionalRef2;
        }

        /**
         * Sets the value of the additionalRef2 property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAdditionalRef2(String value) {
            this.additionalRef2 = value;
        }

        /**
         * Gets the value of the additionalRef3 property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAdditionalRef3() {
            return additionalRef3;
        }

        /**
         * Sets the value of the additionalRef3 property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAdditionalRef3(String value) {
            this.additionalRef3 = value;
        }

        /**
         * Gets the value of the additionalRef4 property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAdditionalRef4() {
            return additionalRef4;
        }

        /**
         * Sets the value of the additionalRef4 property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAdditionalRef4(String value) {
            this.additionalRef4 = value;
        }

    }

}
